//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bridge_destination_transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub source_chain_id: i64,
    pub source_nonce: i64,
    pub destination_chain_id: i64,
    pub destination_tx_hash: Option<String>,
    pub destination_status_code: Option<i16>,
    pub destination_height: Option<i64>,
    pub destination_processed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bridge_source_transactions::Entity",
        from = "(Column::SourceChainId, Column::SourceNonce)",
        to = "(super::bridge_source_transactions::Column::SourceChainId, super::bridge_source_transactions::Column::SourceNonce)",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BridgeSourceTransactions,
}

impl Related<super::bridge_source_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BridgeSourceTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
