//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::EventTypeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bridge_source_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_chain_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_nonce: i64,
    pub event_type: EventTypeEnum,
    pub source_tx_hash: String,
    pub source_height: Option<i64>,
    pub source_from_address: String,
    pub source_to_address: Option<String>,
    pub target_recipient_address: Option<String>,
    pub source_token_address: Option<String>,
    pub destination_token_address: Option<String>,
    pub amount: Option<String>,
    pub value: Option<String>,
    pub l2_gas_limit: Option<i64>,
    pub source_event_timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bridge_destination_transactions::Entity")]
    BridgeDestinationTransactions,
}

impl Related<super::bridge_destination_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BridgeDestinationTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
