//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "celestia_blobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub commitment_hash: String,
    pub transaction_hash: String,
    pub twine_block_hash: String,
    pub height: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
