//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::bridge_destination_transactions::Entity as BridgeDestinationTransactions;
pub use super::bridge_source_transactions::Entity as BridgeSourceTransactions;
pub use super::celestia_blobs::Entity as CelestiaBlobs;
pub use super::last_synced::Entity as LastSynced;
