//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_type_enum"
)]
pub enum TransactionTypeEnum {
    #[sea_orm(string_value = "Deposit")]
    Deposit,
    #[sea_orm(string_value = "Withdraw")]
    Withdraw,
    #[sea_orm(string_value = "ForcedWithdraw")]
    ForcedWithdraw,
}
