//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_type_enum")]
pub enum EventTypeEnum {
    #[sea_orm(string_value = "deposit")]
    Deposit,
    #[sea_orm(string_value = "withdraw")]
    Withdraw,
    #[sea_orm(string_value = "forced_withdraw")]
    ForcedWithdraw,
}
