//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::TransactionTypeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "source_transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chain_id: i64,
    pub destination_chain_id: Option<i64>,
    pub nonce: i64,
    pub transaction_type: TransactionTypeEnum,
    pub block_number: i64,
    pub l1_token: String,
    pub l2_token: String,
    pub l1_address: String,
    pub twine_address: String,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub message: Option<Vec<u8>>,
    pub transaction_hash: Option<String>,
    pub timestamp: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
