//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transaction_flows")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chain_id: i64,
    pub nonce: i64,
    pub handled_at: Option<DateTimeWithTimeZone>,
    pub executed_at: Option<DateTimeWithTimeZone>,
    pub handle_tx_hash: Option<String>,
    pub execute_tx_hash: Option<String>,
    pub handle_block_number: Option<i64>,
    pub execute_block_number: Option<i64>,
    pub handle_status: Option<i16>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub transaction_output: Option<Vec<u8>>,
    pub is_handled: Option<bool>,
    pub is_executed: Option<bool>,
    pub is_completed: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
