//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "twine_batch_l2_blocks")]
pub struct Model {
    pub batch_number: i64,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub hash: Vec<u8>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::twine_transaction_batch::Entity",
        from = "Column::BatchNumber",
        to = "super::twine_transaction_batch::Column::Number",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TwineTransactionBatch,
}

impl Related<super::twine_transaction_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineTransactionBatch.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
