//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "uniswap_pools")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pair: String,
    pub token0: String,
    pub token1: String,
    pub all_pairs_length: i64,
    pub tx_hash: String,
    pub block_number: i64,
    pub block_time: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::uniswap_swaps::Entity")]
    UniswapSwaps,
    #[sea_orm(
        belongs_to = "super::uniswap_tokens::Entity",
        from = "Column::Token0",
        to = "super::uniswap_tokens::Column::Address",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UniswapTokens2,
    #[sea_orm(
        belongs_to = "super::uniswap_tokens::Entity",
        from = "Column::Token1",
        to = "super::uniswap_tokens::Column::Address",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UniswapTokens1,
}

impl Related<super::uniswap_swaps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UniswapSwaps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
