//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "uniswap_swaps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tx_hash: String,
    pub log_index: i32,
    pub pair: String,
    pub sender: String,
    pub to: String,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))")]
    pub amount0_in: Decimal,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))")]
    pub amount1_in: Decimal,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))")]
    pub amount0_out: Decimal,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))")]
    pub amount1_out: Decimal,
    pub block_number: i64,
    pub block_time: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::uniswap_pools::Entity",
        from = "Column::Pair",
        to = "super::uniswap_pools::Column::Pair",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UniswapPools,
}

impl Related<super::uniswap_pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UniswapPools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
