//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sent_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tx_hash: String,
    pub from: String,
    pub l2_token: String,
    #[sea_orm(column_type = "Text")]
    pub to: String,
    pub l1_token: String,
    pub amount: String,
    pub nonce: i64,
    pub chain_id: i64,
    pub block_number: i64,
    pub gas_limit: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
