//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twine_batch_l2_transactions")]
pub struct Model {
    pub batch_number: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::twine_transaction_batch::Entity",
        from = "Column::BatchNumber",
        to = "super::twine_transaction_batch::Column::Number",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TwineTransactionBatch,
}

impl Related<super::twine_transaction_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineTransactionBatch.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
