//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twine_transaction_batch_detail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub batch_number: i32,
    pub l2_transaction_count: i64,
    pub l2_fair_gas_price: Decimal,
    pub chain_id: i64,
    pub l1_transaction_count: i64,
    pub l1_gas_price: Decimal,
    pub commit_id: Option<i64>,
    pub execute_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::twine_lifecycle_l1_transactions::Entity",
        from = "Column::CommitId",
        to = "super::twine_lifecycle_l1_transactions::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    TwineLifecycleL1Transactions2,
    #[sea_orm(
        belongs_to = "super::twine_lifecycle_l1_transactions::Entity",
        from = "Column::ExecuteId",
        to = "super::twine_lifecycle_l1_transactions::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    TwineLifecycleL1Transactions1,
    #[sea_orm(
        belongs_to = "super::twine_transaction_batch::Entity",
        from = "Column::BatchNumber",
        to = "super::twine_transaction_batch::Column::Number",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TwineTransactionBatch,
}

impl Related<super::twine_transaction_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineTransactionBatch.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
