//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twine_l1_withdraw")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub l1_nonce: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_id: i64,
    pub status: i16,
    pub slot_number: i64,
    pub from_address: String,
    pub to_twine_address: String,
    pub l1_token: String,
    pub l2_token: String,
    pub amount: String,
    pub tx_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
