//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twine_l2_withdraw")]
pub struct Model {
    pub from: String,
    pub l2_token: String,
    pub to: String,
    pub l1_token: String,
    pub amount: String,
    pub value: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub nonce: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_id: String,
    pub block_number: String,
    pub gas_limit: String,
    pub tx_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
