//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twine_transaction_batch")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub number: i64,
    pub timestamp: DateTimeWithTimeZone,
    pub start_block: i64,
    pub end_block: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub root_hash: Vec<u8>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::twine_batch_l2_blocks::Entity")]
    TwineBatchL2Blocks,
    #[sea_orm(has_one = "super::twine_batch_l2_transactions::Entity")]
    TwineBatchL2Transactions,
    #[sea_orm(has_one = "super::twine_transaction_batch_detail::Entity")]
    TwineTransactionBatchDetail,
}

impl Related<super::twine_batch_l2_blocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineBatchL2Blocks.def()
    }
}

impl Related<super::twine_batch_l2_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineBatchL2Transactions.def()
    }
}

impl Related<super::twine_transaction_batch_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineTransactionBatchDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
