//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twine_transaction_batch")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub number: i32,
    pub timestamp: DateTimeWithTimeZone,
    pub start_block: i64,
    pub end_block: i64,
    pub root_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::twine_transaction_batch_detail::Entity")]
    TwineTransactionBatchDetail,
}

impl Related<super::twine_transaction_batch_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineTransactionBatchDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
