//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "twine_transaction_batch_detail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub batch_number: i64,
    pub l1_transaction_count: i32,
    pub l2_transaction_count: i32,
    #[sea_orm(column_type = "Decimal(Some((100, 0)))")]
    pub l1_gas_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((100, 0)))")]
    pub l2_fair_gas_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((100, 0)))")]
    pub chain_id: Decimal,
    pub commit_transaction_hash: Option<String>,
    pub finalize_transaction_hash: Option<String>,
    pub committed_at: Option<DateTime>,
    pub finalized_at: Option<DateTime>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::twine_transaction_batch::Entity",
        from = "Column::BatchNumber",
        to = "super::twine_transaction_batch::Column::Number",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TwineTransactionBatch,
}

impl Related<super::twine_transaction_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TwineTransactionBatch.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
